// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ogfi.Modules.Catalog.Persistence;

#nullable disable

namespace Ogfi.Modules.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260817141013_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogfi.Modules.Catalog.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseUomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseUomId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("items", "catalog");
                });

            modelBuilder.Entity("Ogfi.Modules.Catalog.ItemPackagingConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseUomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Denominator")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EffectiveFromBusinessDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveToBusinessDate")
                        .HasColumnType("date");

                    b.Property<long>("Numerator")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PurchaseUomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseUomId");

                    b.HasIndex("PurchaseUomId");

                    b.HasIndex("TenantId", "CatalogItemId", "PurchaseUomId", "EffectiveFromBusinessDate")
                        .IsUnique();

                    b.ToTable("item_packaging_conversions", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_item_pack_conversion_dates", "\"EffectiveToBusinessDate\" IS NULL OR \"EffectiveToBusinessDate\" >= \"EffectiveFromBusinessDate\"");

                            t.HasCheckConstraint("CK_item_pack_conversion_denominator", "\"Denominator\" > 0");

                            t.HasCheckConstraint("CK_item_pack_conversion_numerator", "\"Numerator\" > 0");
                        });
                });

            modelBuilder.Entity("Ogfi.Modules.Catalog.Uom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DimensionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PrecisionScale")
                        .HasColumnType("integer");

                    b.Property<long>("StandardDenominator")
                        .HasColumnType("bigint");

                    b.Property<long>("StandardNumerator")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("uoms", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_uoms_denominator", "\"StandardDenominator\" > 0");

                            t.HasCheckConstraint("CK_uoms_numerator", "\"StandardNumerator\" > 0");

                            t.HasCheckConstraint("CK_uoms_precision", "\"PrecisionScale\" >= 0 AND \"PrecisionScale\" <= 9");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "EA",
                            DimensionCode = "COUNT",
                            Name = "Each",
                            PrecisionScale = 3,
                            StandardDenominator = 1L,
                            StandardNumerator = 1L,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "KG",
                            DimensionCode = "MASS",
                            Name = "Kilogram",
                            PrecisionScale = 3,
                            StandardDenominator = 1L,
                            StandardNumerator = 1L,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "G",
                            DimensionCode = "MASS",
                            Name = "Gram",
                            PrecisionScale = 3,
                            StandardDenominator = 1000L,
                            StandardNumerator = 1L,
                            Status = "ACTIVE"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "CASE",
                            DimensionCode = "PACKAGE",
                            Name = "Case",
                            PrecisionScale = 3,
                            StandardDenominator = 1L,
                            StandardNumerator = 1L,
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("Ogfi.Modules.Catalog.CatalogItem", b =>
                {
                    b.HasOne("Ogfi.Modules.Catalog.Uom", null)
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ogfi.Modules.Catalog.ItemPackagingConversion", b =>
                {
                    b.HasOne("Ogfi.Modules.Catalog.Uom", null)
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ogfi.Modules.Catalog.Uom", null)
                        .WithMany()
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ogfi.Modules.Catalog.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CatalogItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
