// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ogfi.Modules.Audit.Persistence.Migrations;

[DbContext(typeof(AuditDbContext))]
partial class AuditDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("audit")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Ogfi.Modules.Audit.AuditEvent", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<Guid?>("ActorMembershipId").HasColumnType("uuid");
            b.Property<string>("ActorType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid?>("ActorUserId").HasColumnType("uuid");
            b.Property<Guid?>("ApprovalDecisionId").HasColumnType("uuid");
            b.Property<Guid?>("ApprovalTaskId").HasColumnType("uuid");
            b.Property<DateOnly?>("BusinessDate").HasColumnType("date");
            b.Property<string>("CausationId").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ErrorCode").HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<Guid?>("FinanceSourcePostingId").HasColumnType("uuid");
            b.Property<Guid?>("GoodsReceiptId").HasColumnType("uuid");
            b.Property<Guid?>("InventoryMovementId").HasColumnType("uuid");
            b.Property<Guid?>("JournalId").HasColumnType("uuid");
            b.Property<Guid?>("LegalEntityId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("OccurredAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("OutletId").HasColumnType("uuid");
            b.Property<string>("Outcome").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid?>("PurchaseOrderId").HasColumnType("uuid");
            b.Property<Guid>("ResourceId").HasColumnType("uuid");
            b.Property<long?>("ResourceRevision").HasColumnType("bigint");
            b.Property<string>("ResourceType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("SafeEvidenceJson").IsRequired().HasColumnType("jsonb");
            b.Property<Guid?>("SourceEventId").HasColumnType("uuid");
            b.Property<string>("SourceModule").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<Guid?>("WorkflowInstanceId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "CorrelationId", "OccurredAtUtc");
            b.HasIndex("TenantId", "GoodsReceiptId", "OccurredAtUtc");
            b.HasIndex("TenantId", "JournalId", "OccurredAtUtc");
            b.HasIndex("TenantId", "OccurredAtUtc");
            b.HasIndex("TenantId", "PurchaseOrderId", "OccurredAtUtc");
            b.HasIndex("TenantId", "ResourceType", "ResourceId", "OccurredAtUtc");
            b.HasIndex("TenantId", "SourceModule", "SourceEventId", "Action")
                .IsUnique()
                .HasFilter("\"SourceEventId\" IS NOT NULL");
            b.ToTable("audit_events", "audit", t =>
            {
                t.HasCheckConstraint("CK_audit_event_revision", "\"ResourceRevision\" IS NULL OR \"ResourceRevision\" > 0");
                t.HasCheckConstraint("CK_audit_event_safe_evidence_size", "octet_length(\"SafeEvidenceJson\"::text) <= 16384");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.Audit.Rs01TraceProjection", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid?>("ApprovalDecisionId").HasColumnType("uuid");
            b.Property<Guid?>("ApprovalTaskId").HasColumnType("uuid");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<int>("EvidenceEventCount").HasColumnType("integer");
            b.Property<Guid?>("FinanceSourcePostingId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("FirstEventAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("GoodsReceiptId").HasColumnType("uuid");
            b.Property<int>("InventoryMovementCount").HasColumnType("integer");
            b.Property<string>("InventoryMovementIdsJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("InvalidReason").HasMaxLength(600).HasColumnType("character varying(600)");
            b.Property<Guid?>("JournalId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("LastEventAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("MissingLinksJson").IsRequired().HasColumnType("jsonb");
            b.Property<Guid>("PurchaseOrderId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("RebuiltAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("State").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<Guid?>("WorkflowInstanceId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "CorrelationId");
            b.HasIndex("TenantId", "GoodsReceiptId");
            b.HasIndex("TenantId", "JournalId");
            b.HasIndex("TenantId", "PurchaseOrderId")
                .IsUnique()
                .HasFilter("\"GoodsReceiptId\" IS NULL");
            b.HasIndex("TenantId", "PurchaseOrderId", "GoodsReceiptId")
                .IsUnique()
                .HasFilter("\"GoodsReceiptId\" IS NOT NULL");
            b.HasIndex("TenantId", "State", "LastEventAtUtc");
            b.ToTable("rs01_trace_projections", "audit", t =>
            {
                t.HasCheckConstraint("CK_audit_trace_event_count", "\"EvidenceEventCount\" > 0");
                t.HasCheckConstraint("CK_audit_trace_movement_count", "\"InventoryMovementCount\" >= 0");
            });
        });
#pragma warning restore 612, 618
    }
}
