// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ogfi.Modules.DurableOperations.Persistence.Migrations;

[DbContext(typeof(DurableOperationsDbContext))]
partial class DurableOperationsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("operations")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.Operation", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset?>("CancelRequestedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("LegalEntityId").HasColumnType("uuid");
            b.Property<string>("OperationType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("OriginalCausationId").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<Guid>("OriginalSourceEventId").HasColumnType("uuid");
            b.Property<Guid?>("OutletId").HasColumnType("uuid");
            b.Property<string>("OwnerModule").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
            b.Property<string>("ReplayRequestKey").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<bool>("Replayable").HasColumnType("boolean");
            b.Property<Guid?>("RequestedByMembershipId").HasColumnType("uuid");
            b.Property<Guid?>("RequestedByUserId").HasColumnType("uuid");
            b.Property<Guid?>("ResultReferenceId").HasColumnType("uuid");
            b.Property<string>("ResultReferenceType").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("SafeDetailJson").HasColumnType("jsonb");
            b.Property<string>("SafeErrorCode").HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<DateTimeOffset?>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(24).HasColumnType("character varying(24)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<long>("Version").IsConcurrencyToken().HasColumnType("bigint");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "CorrelationId");
            b.HasIndex("TenantId", "OriginalSourceEventId");
            b.HasIndex("TenantId", "ReplayRequestKey").IsUnique();
            b.HasIndex("TenantId", "Status", "CreatedAtUtc");
            b.ToTable("operations", "operations", t =>
            {
                t.HasCheckConstraint("CK_operations_safe_detail_size", "\"SafeDetailJson\" IS NULL OR octet_length(\"SafeDetailJson\"::text) <= 8192");
                t.HasCheckConstraint("CK_operations_status", "\"Status\" IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCEL_REQUESTED','CANCELLED')");
                t.HasCheckConstraint("CK_operations_version", "\"Version\" > 0");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.OperationAttempt", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<int>("AttemptNumber").HasColumnType("integer");
            b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<Guid>("OperationId").HasColumnType("uuid");
            b.Property<string>("OriginalCausationId").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<Guid>("OriginalSourceEventId").HasColumnType("uuid");
            b.Property<string>("SafeDetailJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("SafeErrorCode").HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<DateTimeOffset>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<long>("Version").IsConcurrencyToken().HasColumnType("bigint");
            b.Property<string>("WorkerCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "OperationId")
                .IsUnique()
                .HasFilter("\"Status\" = 'RUNNING'");
            b.HasIndex("TenantId", "OperationId", "AttemptNumber").IsUnique();
            b.ToTable("operation_attempts", "operations", t =>
            {
                t.HasCheckConstraint("CK_operation_attempt_number", "\"AttemptNumber\" > 0");
                t.HasCheckConstraint("CK_operation_attempt_safe_detail_size", "octet_length(\"SafeDetailJson\"::text) <= 8192");
                t.HasCheckConstraint("CK_operation_attempt_status", "\"Status\" IN ('RUNNING','SUCCEEDED','FAILED')");
                t.HasCheckConstraint("CK_operation_attempt_version", "\"Version\" > 0");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.OperationCheckpoint", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("CheckpointKey").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("OccurredAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("OperationId").HasColumnType("uuid");
            b.Property<int>("ProgressPercentage").HasColumnType("integer");
            b.Property<string>("SafeDetailJson").IsRequired().HasColumnType("jsonb");
            b.Property<int>("Sequence").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "OperationId", "Sequence").IsUnique();
            b.ToTable("operation_checkpoints", "operations", t =>
            {
                t.HasCheckConstraint("CK_operation_checkpoint_progress", "\"ProgressPercentage\" BETWEEN 0 AND 100");
                t.HasCheckConstraint("CK_operation_checkpoint_safe_detail_size", "octet_length(\"SafeDetailJson\"::text) <= 8192");
                t.HasCheckConstraint("CK_operation_checkpoint_sequence", "\"Sequence\" > 0");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.ProcessingFailureProjection", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<int>("AttemptCount").HasColumnType("integer");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<Guid?>("CurrentOperationId").HasColumnType("uuid");
            b.Property<string>("FailureClassification").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<DateTimeOffset>("FirstFailedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("LastFailedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("LegalEntityId").HasColumnType("uuid");
            b.Property<string>("OriginalCausationId").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<Guid>("OriginalSourceEventId").HasColumnType("uuid");
            b.Property<Guid?>("OutletId").HasColumnType("uuid");
            b.Property<string>("OwnerModule").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
            b.Property<string>("ProcessorCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<bool>("Replayable").HasColumnType("boolean");
            b.Property<Guid>("ResourceId").HasColumnType("uuid");
            b.Property<string>("ResourceType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("SafeDetailJson").IsRequired().HasColumnType("jsonb");
            b.Property<string>("SafeErrorCode").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<string>("State").IsRequired().HasMaxLength(24).HasColumnType("character varying(24)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<long>("Version").IsConcurrencyToken().HasColumnType("bigint");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "CurrentOperationId");
            b.HasIndex("TenantId", "State", "LastFailedAtUtc");
            b.HasIndex("TenantId", "ProcessorCode", "OriginalSourceEventId").IsUnique();
            b.ToTable("processing_failure_projections", "operations", t =>
            {
                t.HasCheckConstraint("CK_processing_failure_attempts", "\"AttemptCount\" > 0");
                t.HasCheckConstraint("CK_processing_failure_classification", "\"FailureClassification\" IN ('TRANSIENT','BUSINESS','FORGED_TENANT','MALFORMED_CONTRACT','AUTHORIZATION','SECURITY_TERMINAL')");
                t.HasCheckConstraint("CK_processing_failure_safe_detail_size", "octet_length(\"SafeDetailJson\"::text) <= 8192");
                t.HasCheckConstraint("CK_processing_failure_state", "\"State\" IN ('PENDING','RETRY_PENDING','BUSINESS_FAILED','TERMINAL_REJECTED','STALLED','RECOVERED','COMPLETED')");
                t.HasCheckConstraint("CK_processing_failure_version", "\"Version\" > 0");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.WorkerHeartbeat", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid?>("CurrentOrLastSourceId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("LastFailedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("LastIterationStartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("LastSafeErrorCode").HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<DateTimeOffset?>("LastSucceededAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("OldestPendingAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int>("PendingCount").HasColumnType("integer");
            b.Property<int>("RetryPendingCount").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<int>("TerminalFailureCount").HasColumnType("integer");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("WorkerCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "UpdatedAtUtc");
            b.HasIndex("TenantId", "WorkerCode").IsUnique();
            b.ToTable("worker_heartbeats", "operations", t =>
            {
                t.HasCheckConstraint("CK_worker_heartbeat_counts", "\"PendingCount\" >= 0 AND \"RetryPendingCount\" >= 0 AND \"TerminalFailureCount\" >= 0");
            });
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.OperationAttempt", b =>
        {
            b.HasOne("Ogfi.Modules.DurableOperations.Operation", null)
                .WithMany()
                .HasForeignKey("TenantId", "OperationId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.OperationCheckpoint", b =>
        {
            b.HasOne("Ogfi.Modules.DurableOperations.Operation", null)
                .WithMany()
                .HasForeignKey("TenantId", "OperationId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Ogfi.Modules.DurableOperations.ProcessingFailureProjection", b =>
        {
            b.HasOne("Ogfi.Modules.DurableOperations.Operation", null)
                .WithMany()
                .HasForeignKey("TenantId", "CurrentOperationId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Restrict);
        });
#pragma warning restore 612, 618
    }
}
