<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ogfi.Modules.Foundation/Ogfi.Modules.Foundation.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Catalog/Ogfi.Modules.Catalog.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Inventory/Ogfi.Modules.Inventory.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Procurement/Ogfi.Modules.Procurement.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Workflow/Ogfi.Modules.Workflow.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Finance/Ogfi.Modules.Finance.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Audit/Ogfi.Modules.Audit.csproj" />
    <ProjectReference Include="../Ogfi.Modules.DurableOperations/Ogfi.Modules.DurableOperations.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
