<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../Ogfi.BuildingBlocks/Ogfi.BuildingBlocks.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Foundation/Ogfi.Modules.Foundation.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Procurement/Ogfi.Modules.Procurement.csproj" />
    <ProjectReference Include="../Ogfi.Modules.Workflow/Ogfi.Modules.Workflow.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
