using Microsoft.EntityFrameworkCore;
using Ogfi.BuildingBlocks.Multitenancy;
using Ogfi.Modules.Finance;
using Ogfi.Modules.Finance.Persistence;
using Ogfi.Modules.Audit;
using Ogfi.Modules.Audit.Persistence;
using Ogfi.Modules.Foundation.Persistence;
using Ogfi.Modules.Foundation.Security;
using Ogfi.Modules.Inventory;
using Ogfi.Modules.Inventory.Persistence;
using Ogfi.Modules.Procurement;
using Ogfi.Modules.Procurement.Persistence;
using Ogfi.Modules.Workflow;
using Ogfi.Modules.Workflow.Persistence;
using Ogfi.Workers;

var builder = Host.CreateApplicationBuilder(args);
var connectionString = builder.Configuration.GetConnectionString("Postgres") ?? "Host=localhost;Port=5432;Database=ogfi;Username=ogfi;Password=ogfi_dev";
builder.Services.AddScoped<ITenantExecutionContextAccessor, TenantExecutionContextAccessor>();
builder.Services.AddScoped<TenantSessionConnectionInterceptor>();
builder.Services.AddScoped<FoundationApproverResolver>();
builder.Services.AddScoped<WorkflowApprovalService>();
builder.Services.AddScoped<PurchaseOrderApprovalOutcomeService>();
builder.Services.AddScoped<ApprovalSpineProcessor>();
builder.Services.AddScoped<GoodsReceiptPostedConsumer>();
builder.Services.AddScoped<StockConsequenceProcessor>();
builder.Services.AddScoped<FinancePostingService>();
builder.Services.AddScoped<FinancialConsequenceProcessor>();
builder.Services.AddScoped<AuditIngestionService>();
builder.Services.AddScoped<AuditQueryService>();
builder.Services.AddScoped<Rs01TraceProjectionService>();
builder.Services.AddScoped<OutboxDeliveryStore>();
builder.Services.AddSingleton<IStockConsequenceAttemptHook, NoopStockConsequenceAttemptHook>();
builder.Services.AddSingleton<IFinancialConsequenceAttemptHook, NoopFinancialConsequenceAttemptHook>();
builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddDbContext<FoundationDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddDbContext<InventoryDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddDbContext<ProcurementDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddDbContext<WorkflowDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddDbContext<FinanceDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddDbContext<AuditDbContext>((sp, options) => options.UseNpgsql(connectionString).AddInterceptors(sp.GetRequiredService<TenantSessionConnectionInterceptor>()));
builder.Services.AddHostedService<OutboxDispatcherWorker>();
builder.Services.AddHostedService<ApprovalSpineWorker>();
builder.Services.AddHostedService<StockConsequenceWorker>();
builder.Services.AddHostedService<FinancialConsequenceWorker>();
await builder.Build().RunAsync();
