// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ogfi.Modules.Finance.Persistence;

#nullable disable

namespace Ogfi.Modules.Finance.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogfi.Modules.Finance.Account", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("AccountingBookId").HasColumnType("uuid");
                    b.Property<string>("Code").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<string>("NormalBalance").IsRequired().HasMaxLength(10).HasColumnType("character varying(10)");
                    b.Property<bool>("PostingEnabled").HasColumnType("boolean");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "AccountingBookId", "Code").IsUnique();
                    b.ToTable("accounts", "finance");
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.AccountingBook", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Code").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("FunctionalCurrency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                    b.Property<bool>("IsPrimary").HasColumnType("boolean");
                    b.Property<Guid>("LegalEntityId").HasColumnType("uuid");
                    b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "Code").IsUnique();
                    b.HasIndex("TenantId", "LegalEntityId", "IsPrimary").IsUnique().HasFilter("\"IsPrimary\" = TRUE");
                    b.ToTable("accounting_books", "finance");
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AccountingBookId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateOnly>("EndBusinessDate").HasColumnType("date");
                    b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<DateTimeOffset?>("OpenedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("OpenedByUserId").HasColumnType("uuid");
                    b.Property<DateOnly>("StartBusinessDate").HasColumnType("date");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "AccountingBookId", "StartBusinessDate", "EndBusinessDate").IsUnique();
                    b.ToTable("accounting_periods", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_finance_period_dates", "\"EndBusinessDate\" >= \"StartBusinessDate\"");
                        });
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.FinanceSourcePosting", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("AttemptCount").HasColumnType("integer");
                    b.Property<DateOnly>("BusinessDate").HasColumnType("date");
                    b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                    b.Property<string>("ErrorCode").HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("ErrorDetail").HasMaxLength(600).HasColumnType("character varying(600)");
                    b.Property<Guid>("GoodsReceiptId").HasColumnType("uuid");
                    b.Property<string>("GoodsReceiptNumber").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<Guid?>("JournalId").HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("LastAttemptAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("LastReplayByUserId").HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("LastReplayAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("LegalEntityId").HasColumnType("uuid");
                    b.Property<Guid>("OutletId").HasColumnType("uuid");
                    b.Property<string>("PayloadHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("jsonb");
                    b.Property<DateTimeOffset?>("PostedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("PurchaseOrderId").HasColumnType("uuid");
                    b.Property<int>("ReplayCount").HasColumnType("integer");
                    b.Property<Guid>("SourceEventId").HasColumnType("uuid");
                    b.Property<int>("SourceSchemaVersion").HasColumnType("integer");
                    b.Property<string>("SourceType").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("SupplierId").HasColumnType("uuid");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "SourceType", "SourceEventId").IsUnique();
                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");
                    b.ToTable("source_postings", "finance");
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.Journal", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AccountingBookId").HasColumnType("uuid");
                    b.Property<DateOnly>("BusinessDate").HasColumnType("date");
                    b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
                    b.Property<Guid>("GoodsReceiptId").HasColumnType("uuid");
                    b.Property<string>("GoodsReceiptNumber").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<Guid>("LegalEntityId").HasColumnType("uuid");
                    b.Property<string>("Number").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<DateTimeOffset>("PostedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateOnly>("PostingDate").HasColumnType("date");
                    b.Property<string>("PostingRuleCodeSnapshot").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<Guid>("PostingRuleVersionId").HasColumnType("uuid");
                    b.Property<int>("PostingRuleVersionNumber").HasColumnType("integer");
                    b.Property<Guid>("SourceEventId").HasColumnType("uuid");
                    b.Property<Guid>("SourcePostingId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<decimal>("TotalCredit").HasPrecision(19, 4).HasColumnType("numeric(19,4)");
                    b.Property<decimal>("TotalDebit").HasPrecision(19, 4).HasColumnType("numeric(19,4)");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "LegalEntityId", "BusinessDate");
                    b.HasIndex("TenantId", "Number").IsUnique();
                    b.HasIndex("TenantId", "SourcePostingId").IsUnique();
                    b.ToTable("journals", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_finance_journal_balanced", "\"TotalDebit\" = \"TotalCredit\"");
                            t.HasCheckConstraint("CK_finance_journal_positive", "\"TotalDebit\" > 0 AND \"TotalCredit\" > 0");
                        });
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.JournalLine", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountCodeSnapshot").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<Guid>("AccountId").HasColumnType("uuid");
                    b.Property<string>("AccountNameSnapshot").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<Guid>("CatalogItemId").HasColumnType("uuid");
                    b.Property<decimal>("CreditAmount").HasPrecision(19, 4).HasColumnType("numeric(19,4)");
                    b.Property<decimal>("DebitAmount").HasPrecision(19, 4).HasColumnType("numeric(19,4)");
                    b.Property<string>("Description").IsRequired().HasMaxLength(240).HasColumnType("character varying(240)");
                    b.Property<Guid>("GoodsReceiptLineId").HasColumnType("uuid");
                    b.Property<Guid>("JournalId").HasColumnType("uuid");
                    b.Property<int>("LineNumber").HasColumnType("integer");
                    b.Property<Guid>("OutletId").HasColumnType("uuid");
                    b.Property<Guid>("PurchaseOrderId").HasColumnType("uuid");
                    b.Property<Guid>("PurchaseOrderLineId").HasColumnType("uuid");
                    b.Property<decimal>("SourceLineAmount").HasPrecision(19, 4).HasColumnType("numeric(19,4)");
                    b.Property<Guid>("StockLocationId").HasColumnType("uuid");
                    b.Property<Guid>("SupplierId").HasColumnType("uuid");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "GoodsReceiptLineId", "AccountId").IsUnique();
                    b.HasIndex("TenantId", "JournalId", "LineNumber").IsUnique();
                    b.ToTable("journal_lines", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_finance_journal_line_one_side", "(\"DebitAmount\" > 0 AND \"CreditAmount\" = 0) OR (\"CreditAmount\" > 0 AND \"DebitAmount\" = 0)");
                            t.HasCheckConstraint("CK_finance_journal_line_source_amount", "\"SourceLineAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Ogfi.Modules.Finance.PostingRuleVersion", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AccountingBookId").HasColumnType("uuid");
                    b.Property<string>("Code").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CreditAccountId").HasColumnType("uuid");
                    b.Property<Guid>("DebitAccountId").HasColumnType("uuid");
                    b.Property<DateOnly>("EffectiveFromBusinessDate").HasColumnType("date");
                    b.Property<DateOnly?>("EffectiveToBusinessDate").HasColumnType("date");
                    b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<string>("SourceType").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.Property<int>("Version").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasAlternateKey("TenantId", "Id");
                    b.HasIndex("TenantId", "AccountingBookId", "Code", "Version").IsUnique();
                    b.HasIndex("TenantId", "AccountingBookId", "SourceType", "EffectiveFromBusinessDate");
                    b.ToTable("posting_rule_versions", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_finance_rule_accounts", "\"DebitAccountId\" <> \"CreditAccountId\"");
                            t.HasCheckConstraint("CK_finance_rule_dates", "\"EffectiveToBusinessDate\" IS NULL OR \"EffectiveToBusinessDate\" >= \"EffectiveFromBusinessDate\"");
                            t.HasCheckConstraint("CK_finance_rule_version", "\"Version\" > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
