namespace Ogfi.BuildingBlocks.Messaging.Contracts;

public sealed record AuditMaterialActionRecordedV1(
    Guid EventId,
    Guid TenantId,
    string ActorType,
    Guid? ActorUserId,
    Guid? ActorMembershipId,
    string Action,
    string SourceModule,
    string ResourceType,
    Guid ResourceId,
    long? ResourceRevision,
    Guid? LegalEntityId,
    Guid? OutletId,
    DateOnly? BusinessDate,
    DateTimeOffset OccurredAtUtc,
    string Outcome,
    string? ErrorCode,
    string CorrelationId,
    string? CausationId,
    Guid? SourceEventId,
    string SafeEvidenceJson,
    Guid? PurchaseOrderId = null,
    Guid? WorkflowInstanceId = null,
    Guid? ApprovalTaskId = null,
    Guid? ApprovalDecisionId = null,
    Guid? GoodsReceiptId = null,
    Guid? InventoryMovementId = null,
    Guid? FinanceSourcePostingId = null,
    Guid? JournalId = null);
